@echo off
set VIRUS=
set VIRUS_UV_DOSE=
set CSV_INTERVAL=
set IS_DEAD_THRESHOLD=

echo 環境変数のリセット完了しました
echo VIRUS=%VIRUS%
echo VIRUS_UV_DOSE=%VIRUS_UV_DOSE%
echo CSV_INTERVAL=%CSV_INTERVAL%
echo IS_DEAD_THRESHOLD=%IS_DEAD_THRESHOLD%